engines:
  - name: engine01
    port: 8080
    image: registry.example.com/engine01:latest
  - name: engine02
    port: 8082
    image: registry.example.com/engine02:latest
  - name: engine03
    port: 8083
    image: registry.example.com/engine03:latest
  # ... repeat up to engine16
