apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: charters.codexdominion.com
spec:
  group: codexdominion.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                crown:
                  type: string
                seal:
                  type: string
                lineage:
                  type: object
                  properties:
                    origin:
                      type: string
                    legacy:
                      type: string
                    renewal:
                      type: string
                replayPolicy:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                binding:
                  type: object
                  properties:
                    pipeline:
                      type: string
                    dashboard:
                      type: string
                    capsule:
                      type: string
                rights:
                  type: object
                  properties:
                    councils:
                      type: array
                      items:
                        type: string
                    custodians:
                      type: array
                      items:
                        type: string
                notes:
                  type: string
  scope: Namespaced
  names:
    plural: charters
    singular: charter
    kind: Charter
    shortNames:
      - charter
