apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: omegacapsules.codexdominion.com
spec:
  group: codexdominion.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                components:
                  type: array
                  items:
                    type: object
                    properties:
                      summaryScroll:
                        type: string
                      hymnManifest:
                        type: string
                      benedictionScroll:
                        type: string
                crown:
                  type: string
                seal:
                  type: string
                ledgerBinding:
                  type: string
                custodian:
                  type: string
                inheritance:
                  type: string
                transmission:
                  type: string
  scope: Namespaced
  names:
    plural: omegacapsules
    singular: omegacapsule
    kind: OmegaCapsule
    shortNames:
      - ocapsule
